
(function(){
'use strict';
const STORAGE='topopro_v3_projects'; const ACTIVE='topopro_v3_active';
const $=(s,r=document)=>r.querySelector(s); const $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
const modules=[
{id:'dashboard',title:'Dashboard',icon:'⌂',desc:'Panel principal, estado del proyecto y configuración.'},
{id:'compass',title:'Brújula / poligonal',icon:'🧭',desc:'Rumbos, azimuts, proyecciones, cierre y Bowditch.'},
{id:'levelSimple',title:'Nivelación simple',icon:'📏',desc:'Altura de instrumento, desnivel y cota nueva.'},
{id:'levelCompound',title:'Nivelación compuesta',icon:'⛰️',desc:'Libreta altimétrica, cambios de estación y verificación.'},
{id:'levelClosed',title:'Nivelación cerrada',icon:'🔁',desc:'Error de cierre, tolerancia y cotas corregidas.'},
{id:'station',title:'Estación total',icon:'🎯',desc:'Radiación, coordenadas XYZ y nube de puntos.'},
{id:'theodolite',title:'Teodolito',icon:'◴',desc:'Lecturas directa/inversa, promedios y radiación.'},
{id:'tacheometry',title:'Taquimetría',icon:'⌁',desc:'Lecturas de mira, distancia, desnivel, cota y radiación.'},
{id:'coords',title:'Coordenadas / conversiones',icon:'⊕',desc:'Rumbo, azimut, DMS, distancia, pendiente y radiación.'},
{id:'areas',title:'Áreas por coordenadas',icon:'▱',desc:'Área por Gauss, perímetro y croquis técnico.'},
{id:'contours',title:'Curvas de nivel',icon:'≋',desc:'Nube XYZ, interpolación IDW e isolíneas básicas.'},
{id:'profiles',title:'Perfiles',icon:'▰',desc:'Perfil longitudinal tipo guitarra, rasante, corte y relleno.'},
{id:'volumes',title:'Volúmenes',icon:'▥',desc:'Áreas medias, prismoidal y diagrama de masas.'},
{id:'curves',title:'Curvas geométricas',icon:'⌒',desc:'Curvas horizontales y verticales para replanteo.'},
{id:'gnss',title:'GNSS / GPS',icon:'◎',desc:'Latitud, longitud, alturas, ondulación geoidal y datum.'},
{id:'fieldbook',title:'Libreta digital',icon:'✎',desc:'Operador, clima, equipo, ubicación, croquis y observaciones.'},
{id:'manuals',title:'Manuales',icon:'📘',desc:'Manual por módulo con ejemplo precargado y cálculo paso a paso.'}
];
let state={projects:[],activeId:null,active:'dashboard',formulas:true,theme:'light',manualTab:'compass'};
function uid(){return 'p_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,7)}
function num(v,def=0){const n=parseFloat(String(v??'').replace(',','.'));return Number.isFinite(n)?n:def}
function has(v){return v!==undefined&&v!==null&&String(v).trim()!==''}
function rad(d){return d*Math.PI/180} function deg(r){return r*180/Math.PI}
function normAz(a){a=num(a);a=((a%360)+360)%360;return Math.abs(a-360)<1e-10?0:a}
function fmt(v,d=current().meta.decimals){return Number.isFinite(v)?Number(v).toFixed(d):'—'}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function parseDMS(value){if(!has(value))return NaN;if(typeof value==='number')return value;let s=String(value).trim().replace(/[°º]/g,' ').replace(/[′']/g,' ').replace(/[″"]/g,' ').replace(/,/g,'.');let sign=/^-/.test(s)?-1:1;s=s.replace(/^[-+]/,'');const parts=s.split(/\s+/).filter(Boolean).map(Number);if(parts.length===1)return sign*parts[0];return sign*(Math.abs(parts[0]||0)+(parts[1]||0)/60+(parts[2]||0)/3600)}
function toDMS(v){v=num(v);const sign=v<0?'-':'';v=Math.abs(v);const d=Math.floor(v),m=Math.floor((v-d)*60),s=((v-d)*60-m)*60;return `${sign}${d}° ${m}' ${s.toFixed(2)}"`}
function rumboToAz(r){if(!has(r))return NaN;let s=String(r).toUpperCase().replace(/°|º|'|"/g,' ').replace(/,/g,'.').trim();const dirs=s.match(/[NSEW]/g)||[];const nums=s.match(/-?\d+(\.\d+)?/g)||[];const a=nums.length?parseDMS(nums.join(' ')):0;const first=dirs[0],last=dirs[dirs.length-1];if(first==='N'&&last==='E')return a;if(first==='S'&&last==='E')return 180-a;if(first==='S'&&last==='W')return 180+a;if(first==='N'&&last==='W')return 360-a;return parseDMS(r)}
function azToRumbo(az){az=normAz(parseDMS(az));let q,a;if(az<=90){q=['N','E'];a=az}else if(az<=180){q=['S','E'];a=180-az}else if(az<=270){q=['S','W'];a=az-180}else{q=['N','W'];a=360-az}return `${q[0]} ${toDMS(a)} ${q[1]}`}
function angleMean(a,b){a=rad(normAz(a));b=rad(normAz(b));return normAz(deg(Math.atan2(Math.sin(a)+Math.sin(b),Math.cos(a)+Math.cos(b))))}
function current(){return state.projects.find(p=>p.id===state.activeId)||state.projects[0]}
function defaultProject(name='Proyecto topográfico V3'){
return {id:uid(),meta:{name,operator:'',date:new Date().toISOString().slice(0,10),decimals:3,mode:'student',primary:'#0f5bd8',accent:'#10b981',logo:''},modules:{
compass:{type:'closed',startN:1000,startE:1000,method:'bowditch',rows:[{from:'A',to:'B',dist:120,rumbo:'N 45 E',az:''},{from:'B',to:'C',dist:95,rumbo:'S 70 E',az:''},{from:'C',to:'D',dist:110,rumbo:'S 35 W',az:''},{from:'D',to:'A',dist:130,rumbo:'N 55 W',az:''}],result:null},
levelSimple:{benchmark:'BM-1',newPoint:'P-1',knownElev:100,back:1.245,fore:2.015,result:null},
levelCompound:{startElev:100,knownEnd:'',rows:[{point:'BM-1',bs:1.5,is:'',fs:'',dist:0,note:'Cota conocida'},{point:'P-1',bs:'',is:0.65,fs:'',dist:20,note:'Intermedia'},{point:'PC-1',bs:'',is:'',fs:1.8,dist:40,note:'Cambio'},{point:'PC-1',bs:1.2,is:'',fs:'',dist:40,note:'Nueva estación'},{point:'P-2',bs:'',is:0.72,fs:'',dist:65,note:'Intermedia'},{point:'BM-2',bs:'',is:'',fs:1.45,dist:90,note:'Final'}],result:null},
levelClosed:{startElev:100,knownEnd:100,method:'distance',tolerance:0.012,rows:[{point:'BM-1',bs:1.32,is:'',fs:'',dist:0,note:'Inicio'},{point:'P-1',bs:'',is:0.88,fs:'',dist:30,note:''},{point:'PC-1',bs:'',is:'',fs:1.76,dist:65,note:'Cambio'},{point:'PC-1',bs:1.1,is:'',fs:'',dist:65,note:'Nueva estación'},{point:'P-2',bs:'',is:0.955,fs:'',dist:105,note:''},{point:'BM-1',bs:'',is:'',fs:1.185,dist:135,note:'Cierre'}],result:null},
station:{stationName:'E-1',x:5000,y:8000,z:120,azBase:35,hi:1.55,rows:[{point:'P-101',angleH:15,angleV:88.5,mode:'zenith',slope:48.5,hp:1.5,code:'LIM',desc:'Límite'},{point:'P-102',angleH:76.3,angleV:91.2,mode:'zenith',slope:62,hp:1.5,code:'ARB',desc:'Árbol'},{point:'P-103',angleH:142.6,angleV:89.4,mode:'zenith',slope:53.2,hp:1.5,code:'EJE',desc:'Eje'}],result:null},
theodolite:{x:1000,y:1000,z:100,azBase:20,hi:1.45,rows:[{point:'T-1',directH:25.1,inverseH:205.3,directV:4.2,inverseV:355.9,dist:55,hp:1.4,method:'radiación'},{point:'T-2',directH:70.4,inverseH:250.5,directV:-2.5,inverseV:2.3,dist:62,hp:1.4,method:'radiación'}],result:null},
tacheometry:{x:2000,y:2000,z:105,azBase:40,hi:1.5,K:100,C:0,rows:[{point:'Q-1',upper:1.88,middle:1.55,lower:1.22,az:25,vAngle:3.5,code:'TER'},{point:'Q-2',upper:2.1,middle:1.7,lower:1.3,az:85,vAngle:-1.8,code:'BOR'}],result:null},
coords:{rumbo:'S 35 20 00 E',azimuth:124.667,dms:'12 30 45',decimalAngle:12.5125,x1:1000,y1:1000,x2:1090,y2:1150,radX:1000,radY:1000,radAz:60,radDist:80,elev1:100,elev2:108,distSlope:160,result:null},
areas:{rows:[{name:'A',x:1000,y:1000,z:0},{name:'B',x:1120,y:1020,z:0},{name:'C',x:1110,y:1115,z:0},{name:'D',x:980,y:1100,z:0}],result:null},
contours:{interval:1,rows:[{point:'P1',x:0,y:0,z:100},{point:'P2',x:100,y:0,z:102},{point:'P3',x:200,y:10,z:104},{point:'P4',x:0,y:100,z:101},{point:'P5',x:100,y:100,z:103},{point:'P6',x:200,y:100,z:105},{point:'P7',x:30,y:180,z:102},{point:'P8',x:160,y:190,z:106}],result:null},
profiles:{rows:[{prog:0,terrain:100,grade:99.6},{prog:20,terrain:101.1,grade:100},{prog:40,terrain:102.4,grade:100.4},{prog:60,terrain:101.8,grade:100.8},{prog:80,terrain:100.9,grade:101.2},{prog:100,terrain:99.8,grade:101.6}],result:null},
volumes:{method:'average',rows:[{section:'0+000',dist:0,areaCut:0,areaFill:8},{section:'0+020',dist:20,areaCut:3,areaFill:5},{section:'0+040',dist:40,areaCut:10,areaFill:2},{section:'0+060',dist:60,areaCut:16,areaFill:0},{section:'0+080',dist:80,areaCut:8,areaFill:3},{section:'0+100',dist:100,areaCut:2,areaFill:9}],result:null},
curves:{h:{R:80,delta:45,PI:250},v:{g1:2.0,g2:-1.0,L:120,PIV:500,elevPIV:110,step:20},result:null},
gnss:{datum:'WGS84',zone:'UTM 18S / local referencial',rows:[{point:'G-1',lat:-12.0453,lon:-77.0311,hEll:125.6,N:31.2,code:'BM'},{point:'G-2',lat:-12.0442,lon:-77.0298,hEll:126.8,N:31.1,code:'LIM'},{point:'G-3',lat:-12.0461,lon:-77.0289,hEll:124.9,N:31.3,code:'PTO'}],result:null},
fieldbook:{date:new Date().toISOString().slice(0,10),operator:'',equipment:'Estación total / nivel / GPS',weather:'Despejado',location:'Campo de práctica',notes:'Ejemplo de registro de campo.',sketch:'Croquis referencial del eje y puntos levantados.',rows:[{time:'08:00',point:'BM-1',activity:'Reconocimiento',obs:'Cota conocida'},{time:'09:15',point:'E-1',activity:'Instalación',obs:'Equipo centrado y nivelado'},{time:'10:30',point:'P-101',activity:'Radiación',obs:'Punto de límite'}],result:null}
}}}
function load(){try{state.projects=JSON.parse(localStorage.getItem(STORAGE)||'[]');state.activeId=localStorage.getItem(ACTIVE);state.theme=localStorage.getItem('topopro_v3_theme')||'light';state.formulas=localStorage.getItem('topopro_v3_formulas')!=='false'}catch(e){state.projects=[]}if(!state.projects.length){const p=defaultProject();state.projects=[p];state.activeId=p.id}if(!current())state.activeId=state.projects[0].id}
function save(){localStorage.setItem(STORAGE,JSON.stringify(state.projects));localStorage.setItem(ACTIVE,state.activeId);status('Guardado localmente')}
function status(t){$('#status').textContent=t;setTimeout(()=>{$('#status').textContent='Listo'},2600)}
function applyAppearance(){const p=current();document.documentElement.dataset.theme=state.theme;document.documentElement.style.setProperty('--primary',p.meta.primary||'#0f5bd8');document.documentElement.style.setProperty('--accent',p.meta.accent||'#10b981');const logo=$('#brandLogo');logo.innerHTML=p.meta.logo?`<img src="${p.meta.logo}" alt="Logo">`:'TP';$('#themeToggle').checked=state.theme==='dark'}
function render(){applyAppearance();renderProjectSelect();renderNav();renderBindings();renderContent()}
function renderProjectSelect(){const sel=$('#projectSelect');sel.innerHTML=state.projects.map(p=>`<option value="${p.id}" ${p.id===state.activeId?'selected':''}>${esc(p.meta.name)}</option>`).join('')}
function renderNav(){$('#nav').innerHTML=modules.map(m=>`<button data-module="${m.id}" class="${state.active===m.id?'active':''}"><span class="ico">${m.icon}</span><span>${m.title}</span></button>`).join('')}
function renderBindings(){const p=current();$$('[data-bind]').forEach(el=>{const v=getByPath(p,el.dataset.bind);if(el.type==='color')el.value=v||'#000000';else if(document.activeElement!==el)el.value=v??''})}
function getByPath(o,path){return path.split('.').reduce((a,k)=>a?a[k]:undefined,o)}
function setByPath(root,path,value){const parts=path.split('.');let o=root;for(let i=0;i<parts.length-1;i++){if(!o[parts[i]])o[parts[i]]={};o=o[parts[i]]}o[parts.at(-1)]=value}
function setPage(t,s){$('#pageTitle').textContent=t;$('#pageSubtitle').textContent=s}
function renderContent(){const m=modules.find(x=>x.id===state.active)||modules[0];setPage(m.title,m.desc);const map={dashboard:renderDashboard,compass:renderCompass,levelSimple:renderLevelSimple,levelCompound:renderLevelCompound,levelClosed:renderLevelClosed,station:renderStation,theodolite:renderTheodolite,tacheometry:renderTacheometry,coords:renderCoords,areas:renderAreas,contours:renderContours,profiles:renderProfiles,volumes:renderVolumes,curves:renderCurves,gnss:renderGnss,fieldbook:renderFieldbook,manuals:renderManuals};(map[state.active]||renderDashboard)()}
function moduleHeader(key,title,desc,canImport=true){return `<div class="section-title"><div><h3>${title}</h3><small>${desc}</small></div><span class="badge ok">V3 operativo</span></div><div class="toolbar no-print"><button class="btn" data-action="calc" data-calc="${key}">Calcular</button>${canImport?`<label class="btn secondary">Importar<input type="file" data-import="${key}" accept=".csv,.txt,.json" hidden></label>`:''}<button class="btn secondary" data-action="exportCSV" data-target="${key}">CSV</button><button class="btn secondary" data-action="exportXLS" data-target="${key}">Excel</button><button class="btn secondary" data-action="exportJSON" data-target="${key}">JSON</button><button class="btn secondary" data-action="printReport">PDF/Imprimir</button><button class="btn secondary" data-action="showManual" data-target="${key}">Manual</button></div>`}
function formulaBlock(txt){return state.formulas?`<div class="formula"><strong>Fórmula:</strong><br>${txt}</div>`:''}
function input(path,label,type='number'){return `<div class="field"><label>${label}</label><input type="${type}" data-module-field="${path}" value="${esc(getByPath(current().modules,path))}"></div>`}
function select(path,label,opts){const v=getByPath(current().modules,path);return `<div class="field"><label>${label}</label><select data-module-field="${path}">${opts.map(o=>`<option value="${o[0]}" ${v===o[0]?'selected':''}>${o[1]}</option>`).join('')}</select></div>`}
function genericTable(key,cols,rows){return `<div class="table-wrap"><table><thead><tr>${cols.map(c=>`<th>${c.label}</th>`).join('')}<th>Acciones</th></tr></thead><tbody>${rows.map((r,i)=>`<tr>${cols.map(c=>`<td><input ${c.type==='number'?'type="number"':''} data-cell="${key}.rows.${i}.${c.field}" value="${esc(r[c.field])}"></td>`).join('')}<td><div class="row-actions"><button class="btn secondary mini" data-action="insertRow" data-target="${key}" data-index="${i}">+</button><button class="btn secondary mini" data-action="dupRow" data-target="${key}" data-index="${i}">⧉</button><button class="btn danger mini" data-action="delRow" data-target="${key}" data-index="${i}">×</button></div></td></tr>`).join('')}</tbody></table></div>`}
function resultTable(cols,rows){return `<div class="table-wrap"><table><thead><tr>${cols.map(c=>`<th>${c.label}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${cols.map(c=>`<td class="${c.num?'num':''}">${c.num?fmt(r[c.field]):esc(r[c.field])}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}
function kpi(label,value,kind=''){return `<div class="kpi ${kind}"><span>${label}</span><strong>${value}</strong></div>`}
function renderDashboard(){const p=current();const mods=modules.filter(m=>!['dashboard','manuals'].includes(m.id));$('#content').innerHTML=`<div class="grid cards">${mods.map(m=>`<div class="card module-card" data-module="${m.id}"><div class="bigico">${m.icon}</div><h3>${m.title}</h3><p class="muted">${m.desc}</p><span class="badge ok">Listo</span></div>`).join('')}</div><div class="grid two" style="margin-top:16px"><div class="card"><h3>Estado del proyecto</h3><div class="kpis">${kpi('Proyecto',esc(p.meta.name))}${kpi('Responsable',esc(p.meta.operator||'Sin definir'))}${kpi('Módulos',String(mods.length))}${kpi('Versión','3.0')}</div><p class="note">Esta versión integra módulos ampliados, gráficos técnicos tipo comercial, manuales por módulo, ejemplos precargados y exportación local.</p></div><div class="card"><h3>Salidas gráficas comerciales</h3><p>La app genera croquis en planta, perfiles tipo guitarra, curvas de nivel por interpolación, diagramas de masas, gráficos de secciones y vistas de radiación. Todo puede imprimirse desde el navegador.</p><div class="toolbar"><button class="btn" data-module="manuals">Ver manuales</button><button class="btn secondary" data-action="backupProject">Respaldo JSON</button></div></div></div>`}
function renderCompass(){const d=current().modules.compass,r=calcCompass(false);$('#content').innerHTML=`<div class="card">${moduleHeader('compass','Levantamiento con brújula / poligonal','Rumbos, azimuts, proyecciones, error de cierre y corrección por Bowditch o tránsito.')}<div class="form-row">${select('compass.type','Tipo',[['closed','Cerrada'],['open','Abierta']])}${input('compass.startN','Norte inicial')}${input('compass.startE','Este inicial')}${select('compass.method','Ajuste',[['bowditch','Bowditch'],['transit','Tránsito']])}</div>${formulaBlock('ΔN = D·cos(Az), ΔE = D·sin(Az). Error lineal = √(ΣΔN² + ΣΔE²). Bowditch: Cᵢ = -Error·Dᵢ/ΣD.')}${genericTable('compass',[{field:'from',label:'Est.'},{field:'to',label:'A'},{field:'dist',label:'Distancia',type:'number'},{field:'rumbo',label:'Rumbo'},{field:'az',label:'Azimut opc.'}],d.rows)}<div class="kpis">${kpi('Longitud total',fmt(r.total)+' m')}${kpi('Error lineal',fmt(r.closure)+' m',r.closure<1?'ok':r.closure<5?'warn':'bad')}${kpi('Precisión relativa',Number.isFinite(r.precision)?'1:'+fmt(r.precision,0):'∞')}${kpi('Filas inválidas',String(r.warnings),r.warnings?'bad':'ok')}</div><div class="grid two"><div><h3>Croquis técnico en planta</h3><div class="graph">${plotPlan(r.pointsAdjusted.map(p=>({name:p.name,x:p.e,y:p.n})),d.type==='closed')}</div></div><div><h3>Cuadro calculado</h3>${resultTable([{field:'lado',label:'Lado'},{field:'az',label:'Az',num:1},{field:'dN',label:'ΔN',num:1},{field:'dE',label:'ΔE',num:1},{field:'adjN',label:'N corr.',num:1},{field:'adjE',label:'E corr.',num:1}],r.rows.map(x=>({...x,lado:x.from+'-'+x.to})))}</div></div></div>`}
function calcCompass(store=true){const d=current().modules.compass;let sumN=0,sumE=0,total=0;const rows=d.rows.map(row=>{const dist=num(row.dist,NaN),az=has(row.az)?parseDMS(row.az):rumboToAz(row.rumbo);const valid=Number.isFinite(dist)&&Number.isFinite(az);const dN=valid?dist*Math.cos(rad(az)):NaN,dE=valid?dist*Math.sin(rad(az)):NaN;if(valid){sumN+=dN;sumE+=dE;total+=dist}return {...row,dist,az,dN,dE,cN:0,cE:0,adjDN:dN,adjDE:dE,adjN:NaN,adjE:NaN,valid}});const closure=Math.hypot(sumN,sumE),precision=closure?total/closure:Infinity;const sumAbsN=rows.reduce((a,r)=>a+(r.valid?Math.abs(r.dN):0),0),sumAbsE=rows.reduce((a,r)=>a+(r.valid?Math.abs(r.dE):0),0);if(d.type==='closed'){rows.forEach(r=>{if(!r.valid)return;if(d.method==='transit'){r.cN=sumAbsN?-sumN*Math.abs(r.dN)/sumAbsN:0;r.cE=sumAbsE?-sumE*Math.abs(r.dE)/sumAbsE:0}else{r.cN=total?-sumN*r.dist/total:0;r.cE=total?-sumE*r.dist/total:0}r.adjDN=r.dN+r.cN;r.adjDE=r.dE+r.cE})}let n=num(d.startN),e=num(d.startE);const adj=[{name:rows[0]?.from||'Inicio',n,e}];rows.forEach(r=>{if(r.valid){n+=r.adjDN;e+=r.adjDE;r.adjN=n;r.adjE=e;adj.push({name:r.to,n,e})}});const res={rows,total,sumN,sumE,closure,precision,pointsAdjusted:adj,warnings:rows.filter(r=>!r.valid).length};if(store){d.result=res;save();renderCompass();status('Brújula calculada')}return res}
function renderLevelSimple(){const d=current().modules.levelSimple,r=calcLevelSimple(false);$('#content').innerHTML=`<div class="card">${moduleHeader('levelSimple','Nivelación simple','Método de altura de instrumento.',false)}<div class="form-row"><div class="field"><label>Punto conocido</label><input data-module-field="levelSimple.benchmark" value="${esc(d.benchmark)}"></div><div class="field"><label>Punto nuevo</label><input data-module-field="levelSimple.newPoint" value="${esc(d.newPoint)}"></div>${input('levelSimple.knownElev','Cota conocida')}${input('levelSimple.back','Vista atrás')}${input('levelSimple.fore','Vista adelante')}</div>${formulaBlock('HI = Cota conocida + Vista atrás. Cota nueva = HI - Vista adelante. Desnivel = Cota nueva - Cota conocida.')}<div class="kpis">${kpi('Altura instrumento',fmt(r.hi)+' m')}${kpi('Cota nueva',fmt(r.elev)+' m','ok')}${kpi('Desnivel',fmt(r.diff)+' m',r.diff>=0?'ok':'warn')}</div><p class="note">Paso a paso: se suma la vista atrás a la cota conocida para obtener HI y luego se resta la vista adelante para obtener la cota del nuevo punto.</p></div>`}
function calcLevelSimple(store=true){const d=current().modules.levelSimple;const hi=num(d.knownElev)+num(d.back),elev=hi-num(d.fore),diff=elev-num(d.knownElev);const res={hi,elev,diff,rows:[{punto:d.benchmark,cota:num(d.knownElev),lectura:'VA '+d.back},{punto:d.newPoint,cota:elev,lectura:'VF '+d.fore}]};if(store){d.result=res;save();renderLevelSimple();status('Nivelación simple calculada')}return res}
function levelCols(){return[{field:'point',label:'Punto'},{field:'bs',label:'VA',type:'number'},{field:'is',label:'VI',type:'number'},{field:'fs',label:'VF',type:'number'},{field:'dist',label:'Dist. acum.',type:'number'},{field:'note',label:'Nota'}]}
function renderLevelCompound(){const d=current().modules.levelCompound,r=calcLevelCompound(false);$('#content').innerHTML=`<div class="card">${moduleHeader('levelCompound','Nivelación compuesta','Puntos de cambio, vistas atrás, intermedias y adelante.')}${input('levelCompound.startElev','Cota inicial')}${formulaBlock('HI = Cota punto + VA. Cota punto observado = HI - VI o VF. Verificación: ΣVA - ΣVF = Cota final - Cota inicial.')}${genericTable('levelCompound',levelCols(),d.rows)}<div class="kpis">${kpi('Σ VA',fmt(r.sumBS))}${kpi('Σ VF',fmt(r.sumFS))}${kpi('Cota final calc.',fmt(r.finalElev)+' m')}${kpi('Δ cotas',fmt(r.delta)+' m')}</div><div class="grid two"><div><h3>Perfil longitudinal tipo guitarra</h3><div class="graph tall">${plotProfileGuitar(r.rows)}</div></div><div><h3>Libreta calculada</h3>${resultTable([{field:'point',label:'Punto'},{field:'hi',label:'HI',num:1},{field:'elev',label:'Cota',num:1},{field:'dist',label:'Dist',num:1},{field:'note',label:'Nota'}],r.rows)}</div></div></div>`}
function calcLevelCompound(store=true){const d=current().modules.levelCompound;let elev=num(d.startElev),hi=NaN,last=elev,sumBS=0,sumFS=0;const rows=d.rows.map((row,i)=>{let r={...row,dist:num(row.dist,i),hi:NaN,elev:NaN};if(i===0){r.elev=elev;last=elev}if(has(row.bs)){if(!Number.isFinite(r.elev))r.elev=last;hi=r.elev+num(row.bs);r.hi=hi;sumBS+=num(row.bs)}if(has(row.is)||has(row.fs)){const read=has(row.is)?num(row.is):num(row.fs);if(Number.isFinite(hi)){r.elev=hi-read;last=r.elev}if(has(row.fs))sumFS+=num(row.fs)}if(!Number.isFinite(r.hi)&&Number.isFinite(hi))r.hi=hi;return r});const finalElev=[...rows].reverse().find(x=>Number.isFinite(x.elev))?.elev??elev;const delta=finalElev-num(d.startElev);const res={rows,sumBS,sumFS,finalElev,delta};if(store){d.result=res;save();renderLevelCompound();status('Nivelación compuesta calculada')}return res}
function renderLevelClosed(){const d=current().modules.levelClosed,r=calcLevelClosed(false);$('#content').innerHTML=`<div class="card">${moduleHeader('levelClosed','Nivelación cerrada','Cierre altimétrico, tolerancia y corrección proporcional.')}<div class="form-row">${input('levelClosed.startElev','Cota inicial')}${input('levelClosed.knownEnd','Cota final conocida')}${input('levelClosed.tolerance','Tolerancia')}${select('levelClosed.method','Corrección',[['distance','Por distancia'],['stations','Por estaciones']])}</div>${formulaBlock('Error = Cota calculada final - Cota final conocida. Correcciónᵢ = -Error·factor acumulado.')} ${genericTable('levelClosed',levelCols(),d.rows)}<div class="kpis">${kpi('Error cierre',fmt(r.error)+' m',Math.abs(r.error)<=num(d.tolerance)?'ok':'bad')}${kpi('Tolerancia',fmt(num(d.tolerance))+' m')}${kpi('Cota final corregida',fmt(r.correctedEnd)+' m','ok')}${kpi('Semáforo',r.ok?'Verde':'Rojo',r.ok?'ok':'bad')}</div><div class="grid two"><div><h3>Perfil corregido tipo guitarra</h3><div class="graph tall">${plotProfileGuitar(r.rows)}</div></div><div><h3>Cotas corregidas</h3>${resultTable([{field:'point',label:'Punto'},{field:'elev',label:'Cota calc.',num:1},{field:'correction',label:'Corrección',num:1},{field:'elevCorr',label:'Cota corr.',num:1}],r.rows)}</div></div></div>`}
function calcLevelClosed(store=true){const d=current().modules.levelClosed;const temp={startElev:d.startElev,rows:d.rows};const old=current().modules.levelCompound;current().modules.levelCompound=temp;const base=calcLevelCompound(false);current().modules.levelCompound=old;const error=base.finalElev-num(d.knownEnd),totalDist=Math.max(...base.rows.map(r=>num(r.dist,0)),1),n=base.rows.length;const rows=base.rows.map((r,i)=>{const f=d.method==='stations'?(i/(n-1||1)):(num(r.dist,0)/totalDist);const correction=-error*f;return {...r,correction,elevCorr:Number.isFinite(r.elev)?r.elev+correction:NaN}});const ok=Math.abs(error)<=num(d.tolerance);const res={...base,error,totalDist,ok,rows,correctedEnd:rows.at(-1)?.elevCorr};if(store){d.result=res;save();renderLevelClosed();status('Nivelación cerrada calculada')}return res}
function renderStation(){const d=current().modules.station,r=calcStation(false);$('#content').innerHTML=`<div class="card">${moduleHeader('station','Estación total','Radiación por ángulo horizontal, ángulo vertical/cenital y distancia inclinada.')}<div class="form-row"><div class="field"><label>Estación</label><input data-module-field="station.stationName" value="${esc(d.stationName)}"></div>${input('station.x','Este estación')}${input('station.y','Norte estación')}${input('station.z','Cota estación')}${input('station.azBase','Azimut base')}${input('station.hi','Altura instrumento')}</div>${formulaBlock('Az = Az base + AH. Si Z es cenital: DH = DI·sen(Z), ΔZ = DI·cos(Z)+HI-HP.')} ${genericTable('station',[{field:'point',label:'Punto'},{field:'angleH',label:'AH',type:'number'},{field:'angleV',label:'AV/Z',type:'number'},{field:'mode',label:'Modo'},{field:'slope',label:'DI',type:'number'},{field:'hp',label:'HP',type:'number'},{field:'code',label:'Código'},{field:'desc',label:'Desc.'}],d.rows)}<div class="grid two"><div><h3>Radiación en planta</h3><div class="graph">${plotPlan([{name:d.stationName,x:num(d.x),y:num(d.y),station:true},...r.rows.map(p=>({name:p.point,x:p.x,y:p.y}))],false)}</div></div><div><h3>Coordenadas calculadas</h3>${resultTable([{field:'point',label:'Punto'},{field:'az',label:'Az',num:1},{field:'dh',label:'DH',num:1},{field:'dz',label:'Desnivel',num:1},{field:'x',label:'Este',num:1},{field:'y',label:'Norte',num:1},{field:'z',label:'Cota',num:1}],r.rows)}</div></div></div>`}
function calcStation(store=true){const d=current().modules.station;const rows=d.rows.map(row=>radiateRow(row,{x:num(d.x),y:num(d.y),z:num(d.z),azBase:parseDMS(d.azBase),hi:num(d.hi)}));const res={rows};if(store){d.result=res;save();renderStation();status('Estación total calculada')}return res}
function radiateRow(row,base){const az=normAz(base.azBase+parseDMS(row.angleH||row.az||0));const di=num(row.slope||row.dist,NaN),av=parseDMS(row.angleV??row.vAngle??0);let dh,dz;if((row.mode||'zenith').toLowerCase().startsWith('zen')){dh=di*Math.sin(rad(av));dz=di*Math.cos(rad(av))+base.hi-num(row.hp,0)}else{dh=di*Math.cos(rad(av));dz=di*Math.sin(rad(av))+base.hi-num(row.hp,0)}const x=base.x+dh*Math.sin(rad(az)),y=base.y+dh*Math.cos(rad(az)),z=base.z+dz;return {...row,az,dh,dz,x,y,z}}
function renderTheodolite(){const d=current().modules.theodolite,r=calcTheodolite(false);$('#content').innerHTML=`<div class="card">${moduleHeader('theodolite','Teodolito','Promedia lecturas directa/inversa y calcula radiación.')}<div class="form-row">${input('theodolite.x','Este estación')}${input('theodolite.y','Norte estación')}${input('theodolite.z','Cota estación')}${input('theodolite.azBase','Azimut base')}${input('theodolite.hi','Altura instrumento')}</div>${formulaBlock('Lectura inversa horizontal corregida = HI - 180°. AH promedio = media angular(PD, PI corregida). Az = Az base + AH promedio.')} ${genericTable('theodolite',[{field:'point',label:'Punto'},{field:'directH',label:'H directa',type:'number'},{field:'inverseH',label:'H inversa',type:'number'},{field:'directV',label:'V directa',type:'number'},{field:'inverseV',label:'V inversa',type:'number'},{field:'dist',label:'Distancia',type:'number'},{field:'hp',label:'Alt. señal',type:'number'},{field:'method',label:'Método'}],d.rows)}<div class="grid two"><div><h3>Gráfico polar / radiación</h3><div class="graph">${plotPlan([{name:'Est.',x:num(d.x),y:num(d.y),station:true},...r.rows.map(p=>({name:p.point,x:p.x,y:p.y}))],false)}</div></div><div><h3>Resultados</h3>${resultTable([{field:'point',label:'Punto'},{field:'hMean',label:'H prom.',num:1},{field:'vMean',label:'V prom.',num:1},{field:'az',label:'Az',num:1},{field:'x',label:'Este',num:1},{field:'y',label:'Norte',num:1},{field:'z',label:'Cota',num:1}],r.rows)}</div></div></div>`}
function calcTheodolite(store=true){const d=current().modules.theodolite;const rows=d.rows.map(row=>{const invH=normAz(num(row.inverseH)-180),hMean=angleMean(num(row.directH),invH),vMean=(num(row.directV)+(360-num(row.inverseV)))/2;const az=normAz(num(d.azBase)+hMean),dh=num(row.dist),dz=dh*Math.tan(rad(vMean))+num(d.hi)-num(row.hp);const x=num(d.x)+dh*Math.sin(rad(az)),y=num(d.y)+dh*Math.cos(rad(az)),z=num(d.z)+dz;return {...row,hMean,vMean,az,dh,dz,x,y,z}});const res={rows};if(store){d.result=res;save();renderTheodolite();status('Teodolito calculado')}return res}
function renderTacheometry(){const d=current().modules.tacheometry,r=calcTacheometry(false);$('#content').innerHTML=`<div class="card">${moduleHeader('tacheometry','Taquimetría','Lecturas de mira, intervalo estadimétrico, distancia, desnivel, cota y coordenadas.')}<div class="form-row">${input('tacheometry.x','Este estación')}${input('tacheometry.y','Norte estación')}${input('tacheometry.z','Cota estación')}${input('tacheometry.azBase','Azimut base')}${input('tacheometry.hi','Altura instrumento')}${input('tacheometry.K','Constante K')}${input('tacheometry.C','Constante C')}</div>${formulaBlock('s = LS - LI. DH ≈ K·s·cos²(α) + C·cos(α). ΔH = DH·tan(α) + HI - lectura media.')} ${genericTable('tacheometry',[{field:'point',label:'Punto'},{field:'upper',label:'LS',type:'number'},{field:'middle',label:'LM',type:'number'},{field:'lower',label:'LI',type:'number'},{field:'az',label:'AH/Az',type:'number'},{field:'vAngle',label:'Ángulo vertical',type:'number'},{field:'code',label:'Código'}],d.rows)}<div class="grid two"><div><h3>Radiación taquimétrica</h3><div class="graph">${plotPlan([{name:'Est.',x:num(d.x),y:num(d.y),station:true},...r.rows.map(p=>({name:p.point,x:p.x,y:p.y}))],false)}</div></div><div><h3>Tabla calculada</h3>${resultTable([{field:'point',label:'Punto'},{field:'s',label:'s',num:1},{field:'dh',label:'DH',num:1},{field:'dz',label:'Desnivel',num:1},{field:'x',label:'Este',num:1},{field:'y',label:'Norte',num:1},{field:'z',label:'Cota',num:1}],r.rows)}</div></div></div>`}
function calcTacheometry(store=true){const d=current().modules.tacheometry;const rows=d.rows.map(row=>{const s=num(row.upper)-num(row.lower),a=parseDMS(row.vAngle),dh=num(d.K)*s*Math.cos(rad(a))**2+num(d.C)*Math.cos(rad(a)),dz=dh*Math.tan(rad(a))+num(d.hi)-num(row.middle),az=normAz(num(d.azBase)+parseDMS(row.az));const x=num(d.x)+dh*Math.sin(rad(az)),y=num(d.y)+dh*Math.cos(rad(az)),z=num(d.z)+dz;return {...row,s,dh,dz,az,x,y,z}});const res={rows};if(store){d.result=res;save();renderTacheometry();status('Taquimetría calculada')}return res}
function renderCoords(){const d=current().modules.coords,r=calcCoords(false);$('#content').innerHTML=`<div class="card">${moduleHeader('coords','Coordenadas y conversiones','Herramientas rápidas de ángulos, coordenadas y pendientes.',false)}${formulaBlock('Distancia = √(ΔE² + ΔN²). Azimut = atan2(ΔE, ΔN). Pendiente % = ΔH/DH·100.')}<div class="form-row">${input('coords.rumbo','Rumbo','text')}${input('coords.azimuth','Azimut')}${input('coords.dms','GMS','text')}${input('coords.decimalAngle','Grado decimal')}${input('coords.x1','E1')}${input('coords.y1','N1')}${input('coords.x2','E2')}${input('coords.y2','N2')}${input('coords.radX','E radiación')}${input('coords.radY','N radiación')}${input('coords.radAz','Az radiación')}${input('coords.radDist','Dist radiación')}${input('coords.elev1','Cota 1')}${input('coords.elev2','Cota 2')}${input('coords.distSlope','Dist. horizontal')}</div><div class="kpis">${kpi('Rumbo → Azimut',fmt(r.azFromRumbo)+'°')}${kpi('Azimut → Rumbo',esc(r.rumboFromAz))}${kpi('GMS → Decimal',fmt(r.decFromDms)+'°')}${kpi('Decimal → GMS',esc(r.dmsFromDec))}${kpi('Distancia 1-2',fmt(r.dist)+' m')}${kpi('Azimut 1-2',fmt(r.az12)+'°')}${kpi('Punto radiado E,N',`${fmt(r.radX)}, ${fmt(r.radY)}`)}${kpi('Pendiente',fmt(r.slopePct)+' %')}</div></div>`}
function calcCoords(store=true){const d=current().modules.coords;const dx=num(d.x2)-num(d.x1),dy=num(d.y2)-num(d.y1),dist=Math.hypot(dx,dy),az12=normAz(deg(Math.atan2(dx,dy))),azr=normAz(parseDMS(d.radAz)),rd=num(d.radDist),dz=num(d.elev2)-num(d.elev1);const res={azFromRumbo:rumboToAz(d.rumbo),rumboFromAz:azToRumbo(d.azimuth),decFromDms:parseDMS(d.dms),dmsFromDec:toDMS(num(d.decimalAngle)),dist,az12,radX:num(d.radX)+rd*Math.sin(rad(azr)),radY:num(d.radY)+rd*Math.cos(rad(azr)),slopePct:dz/(num(d.distSlope)||1)*100,slopeDeg:deg(Math.atan(dz/(num(d.distSlope)||1))),rows:[{concepto:'Distancia',valor:dist},{concepto:'Azimut',valor:az12},{concepto:'Pendiente %',valor:dz/(num(d.distSlope)||1)*100}]};if(store){d.result=res;save();renderCoords();status('Conversiones calculadas')}return res}
function renderAreas(){const d=current().modules.areas,r=calcAreas(false);$('#content').innerHTML=`<div class="card">${moduleHeader('areas','Áreas por coordenadas','Método de Gauss, perímetro y conversión de unidades.')} ${formulaBlock('A = 1/2 · |Σ(Eᵢ·Nᵢ₊₁ - Nᵢ·Eᵢ₊₁)|.')} ${genericTable('areas',[{field:'name',label:'Vértice'},{field:'x',label:'Este',type:'number'},{field:'y',label:'Norte',type:'number'},{field:'z',label:'Cota',type:'number'}],d.rows)}<div class="kpis">${kpi('Área',fmt(r.area)+' m²','ok')}${kpi('Hectáreas',fmt(r.ha)+' ha')}${kpi('km²',fmt(r.km2)+' km²')}${kpi('Perímetro',fmt(r.perimeter)+' m')}</div><div class="graph">${plotPlan(r.points,true)}</div></div>`}
function calcAreas(store=true){const d=current().modules.areas;const pts=d.rows.map(r=>({name:r.name,x:num(r.x,NaN),y:num(r.y,NaN),z:num(r.z,0)})).filter(p=>Number.isFinite(p.x)&&Number.isFinite(p.y));let s=0,per=0;for(let i=0;i<pts.length;i++){const a=pts[i],b=pts[(i+1)%pts.length];s+=a.x*b.y-a.y*b.x;per+=Math.hypot(b.x-a.x,b.y-a.y)}const area=Math.abs(s)/2,res={area,ha:area/10000,km2:area/1e6,perimeter:per,points:pts,rows:pts};if(store){d.result=res;save();renderAreas();status('Área calculada')}return res}
function renderContours(){const d=current().modules.contours,r=calcContours(false);$('#content').innerHTML=`<div class="card">${moduleHeader('contours','Curvas de nivel','Interpolación IDW referencial, nube de puntos y curvas básicas.')}<div class="form-row">${input('contours.interval','Equidistancia')}</div>${formulaBlock('Se genera una malla regular y se estima Z por IDW: Z = Σ(zᵢ / dᵢ²) / Σ(1 / dᵢ²). Luego se trazan isolíneas por nivel.')} ${genericTable('contours',[{field:'point',label:'Punto'},{field:'x',label:'X',type:'number'},{field:'y',label:'Y',type:'number'},{field:'z',label:'Z',type:'number'}],d.rows)}<div class="grid two"><div><h3>Mapa de curvas de nivel</h3><div class="graph">${plotContours(d.rows,num(d.interval))}</div></div><div><h3>Niveles generados</h3><div class="kpis">${kpi('Cota mínima',fmt(r.minZ)+' m')}${kpi('Cota máxima',fmt(r.maxZ)+' m')}${kpi('N° curvas',String(r.levels.length))}${kpi('Equidistancia',fmt(num(d.interval))+' m')}</div><p class="note">Las curvas son referenciales para análisis académico. Para uso profesional debe densificarse el levantamiento y confirmar datum/sistema de referencia.</p></div></div></div>`}
function calcContours(store=true){const d=current().modules.contours;const zs=d.rows.map(r=>num(r.z,NaN)).filter(Number.isFinite);const minZ=Math.min(...zs),maxZ=Math.max(...zs),int=num(d.interval,1)||1;const levels=[];for(let z=Math.ceil(minZ/int)*int;z<=maxZ+1e-9;z+=int)levels.push(z);const res={rows:d.rows,minZ,maxZ,levels};if(store){d.result=res;save();renderContours();status('Curvas generadas')}return res}
function renderProfiles(){const d=current().modules.profiles,r=calcProfiles(false);$('#content').innerHTML=`<div class="card">${moduleHeader('profiles','Perfiles longitudinales y transversales','Perfil tipo guitarra con terreno, rasante, corte y relleno.')} ${formulaBlock('Pendiente = Δcota / Δprogresiva · 100. Corte = max(Terreno - Rasante, 0). Relleno = max(Rasante - Terreno, 0).')} ${genericTable('profiles',[{field:'prog',label:'Progresiva',type:'number'},{field:'terrain',label:'Terreno',type:'number'},{field:'grade',label:'Rasante',type:'number'}],d.rows)}<div class="grid two"><div><h3>Perfil tipo guitarra</h3><div class="graph tall">${plotRoadProfile(r.rows)}</div></div><div><h3>Corte / relleno</h3>${resultTable([{field:'prog',label:'Prog.',num:1},{field:'terrain',label:'Terreno',num:1},{field:'grade',label:'Rasante',num:1},{field:'cut',label:'Corte',num:1},{field:'fill',label:'Relleno',num:1},{field:'slope',label:'Pendiente %',num:1}],r.rows)}</div></div></div>`}
function calcProfiles(store=true){const d=current().modules.profiles;const rows=d.rows.map((r,i,arr)=>{const cut=Math.max(num(r.terrain)-num(r.grade),0),fill=Math.max(num(r.grade)-num(r.terrain),0);let slope=NaN;if(i>0){const prev=arr[i-1];slope=(num(r.grade)-num(prev.grade))/(num(r.prog)-num(prev.prog)||1)*100}return {...r,prog:num(r.prog),terrain:num(r.terrain),grade:num(r.grade),cut,fill,slope}});const res={rows};if(store){d.result=res;save();renderProfiles();status('Perfil calculado')}return res}
function renderVolumes(){const d=current().modules.volumes,r=calcVolumes(false);$('#content').innerHTML=`<div class="card">${moduleHeader('volumes','Movimiento de tierras / volúmenes','Áreas medias, prismoidal básico y diagrama de masas.')}<div class="form-row">${select('volumes.method','Método',[['average','Áreas medias'],['prismoidal','Prismoidal simplificado']])}</div>${formulaBlock('Áreas medias: V = ((A₁ + A₂) / 2) · L. Balance acumulado = ΣVcorte - ΣVrelleno.')} ${genericTable('volumes',[{field:'section',label:'Sección'},{field:'dist',label:'Distancia',type:'number'},{field:'areaCut',label:'Área corte',type:'number'},{field:'areaFill',label:'Área relleno',type:'number'}],d.rows)}<div class="kpis">${kpi('Vol. corte',fmt(r.totalCut)+' m³','ok')}${kpi('Vol. relleno',fmt(r.totalFill)+' m³','warn')}${kpi('Balance',fmt(r.balance)+' m³',r.balance>=0?'ok':'warn')}</div><div class="grid two"><div><h3>Diagrama de masas</h3><div class="graph">${plotMassHaul(r.rows)}</div></div><div><h3>Volúmenes parciales</h3>${resultTable([{field:'section',label:'Tramo'},{field:'cutVol',label:'Corte m³',num:1},{field:'fillVol',label:'Relleno m³',num:1},{field:'mass',label:'Masa acum.',num:1}],r.rows)}</div></div></div>`}
function calcVolumes(store=true){const d=current().modules.volumes;let totalCut=0,totalFill=0,mass=0;const rows=d.rows.map((r,i,arr)=>{let cutVol=0,fillVol=0;if(i>0){const prev=arr[i-1],L=num(r.dist)-num(prev.dist);cutVol=(num(prev.areaCut)+num(r.areaCut))/2*L;fillVol=(num(prev.areaFill)+num(r.areaFill))/2*L;totalCut+=cutVol;totalFill+=fillVol;mass+=cutVol-fillVol}return {...r,dist:num(r.dist),cutVol,fillVol,mass}});const res={rows,totalCut,totalFill,balance:totalCut-totalFill};if(store){d.result=res;save();renderVolumes();status('Volúmenes calculados')}return res}
function renderCurves(){const d=current().modules.curves,r=calcCurves(false);$('#content').innerHTML=`<div class="card">${moduleHeader('curves','Curvas horizontales y verticales','Elementos geométricos para replanteo. ',false)}<h3>Curva horizontal</h3><div class="form-row">${input('curves.h.R','Radio R')}${input('curves.h.delta','Ángulo Δ')}${input('curves.h.PI','Progresiva PI')}</div><h3>Curva vertical</h3><div class="form-row">${input('curves.v.g1','Pendiente inicial %')}${input('curves.v.g2','Pendiente final %')}${input('curves.v.L','Longitud')}${input('curves.v.PIV','Prog. PIV')}${input('curves.v.elevPIV','Cota PIV')}${input('curves.v.step','Intervalo')}</div>${formulaBlock('Horizontal: T = R·tan(Δ/2), L = πRΔ/180. Vertical parabólica: y = PVC + g₁x + ((g₂-g₁)/(2L))x².')}<div class="grid two"><div><h3>Elementos horizontales</h3><div class="kpis">${kpi('T',fmt(r.h.T))}${kpi('L curva',fmt(r.h.L))}${kpi('PC',fmt(r.h.PC))}${kpi('PT',fmt(r.h.PT))}</div><div class="graph">${plotCurveSketch(r.h)}</div></div><div><h3>Tabla vertical</h3>${resultTable([{field:'prog',label:'Prog.',num:1},{field:'x',label:'x',num:1},{field:'elev',label:'Cota',num:1}],r.v.table)}<div class="graph">${plotVerticalCurve(r.v.table)}</div></div></div></div>`}
function calcCurves(store=true){const d=current().modules.curves,h=d.h,v=d.v,R=num(h.R),D=num(h.delta),PI=num(h.PI);const T=R*Math.tan(rad(D/2)),L=Math.PI*R*D/180,CL=2*R*Math.sin(rad(D/2)),E=R*(1/Math.cos(rad(D/2))-1),M=R*(1-Math.cos(rad(D/2))),PC=PI-T,PT=PC+L;const g1=num(v.g1)/100,g2=num(v.g2)/100,LV=num(v.L),PVC=num(v.PIV)-LV/2,ePVC=num(v.elevPIV)-g1*LV/2,step=Math.max(1,num(v.step,20));const table=[];for(let x=0;x<=LV+1e-9;x+=step){table.push({prog:PVC+x,x,elev:ePVC+g1*x+((g2-g1)/(2*LV))*x*x})}if(table.at(-1)?.x<LV)table.push({prog:PVC+LV,x:LV,elev:ePVC+g1*LV+((g2-g1)/(2*LV))*LV*LV});const res={h:{R,D,T,L,CL,E,M,PC,PT,PI},v:{PVC,PVT:PVC+LV,table}};if(store){d.result=res;save();renderCurves();status('Curvas calculadas')}return res}
function renderGnss(){const d=current().modules.gnss,r=calcGnss(false);$('#content').innerHTML=`<div class="card">${moduleHeader('gnss','GNSS / GPS topográfico','Coordenadas geográficas, altura elipsoidal, ondulación y altura ortométrica.')}<div class="form-row"><div class="field"><label>Datum</label><input data-module-field="gnss.datum" value="${esc(d.datum)}"></div><div class="field"><label>Sistema / zona</label><input data-module-field="gnss.zone" value="${esc(d.zone)}"></div></div>${formulaBlock('Altura ortométrica aproximada: H = h - N, donde h es altura elipsoidal y N la ondulación geoidal ingresada.')} ${genericTable('gnss',[{field:'point',label:'Punto'},{field:'lat',label:'Latitud',type:'number'},{field:'lon',label:'Longitud',type:'number'},{field:'hEll',label:'h elipsoidal',type:'number'},{field:'N',label:'Ondulación N',type:'number'},{field:'code',label:'Código'}],d.rows)}<div class="grid two"><div><h3>Puntos GNSS</h3><div class="graph">${plotPlan(r.rows.map(x=>({name:x.point,x:x.lon,y:x.lat})),false)}</div></div><div><h3>Alturas</h3>${resultTable([{field:'point',label:'Punto'},{field:'latDms',label:'Lat DMS'},{field:'lonDms',label:'Lon DMS'},{field:'H',label:'H ortométrica',num:1}],r.rows)}<p class="note">Advertencia: para entregar planos oficiales debe confirmarse datum, geoid model, zona UTM y precisión del equipo.</p></div></div></div>`}
function calcGnss(store=true){const d=current().modules.gnss;const rows=d.rows.map(r=>({...r,lat:num(r.lat),lon:num(r.lon),H:num(r.hEll)-num(r.N),latDms:toDMS(num(r.lat)),lonDms:toDMS(num(r.lon))}));const res={rows};if(store){d.result=res;save();renderGnss();status('GNSS procesado')}return res}
function renderFieldbook(){const d=current().modules.fieldbook,r=calcFieldbook(false);$('#content').innerHTML=`<div class="card">${moduleHeader('fieldbook','Libreta de campo digital','Registro ordenado del trabajo de campo.',true)}<div class="form-row"><div class="field"><label>Fecha</label><input type="date" data-module-field="fieldbook.date" value="${esc(d.date)}"></div><div class="field"><label>Operador</label><input data-module-field="fieldbook.operator" value="${esc(d.operator)}"></div><div class="field"><label>Equipo</label><input data-module-field="fieldbook.equipment" value="${esc(d.equipment)}"></div><div class="field"><label>Clima</label><input data-module-field="fieldbook.weather" value="${esc(d.weather)}"></div><div class="field"><label>Ubicación</label><input data-module-field="fieldbook.location" value="${esc(d.location)}"></div></div><div class="form-row"><div class="field"><label>Observaciones</label><textarea data-module-field="fieldbook.notes">${esc(d.notes)}</textarea></div><div class="field"><label>Croquis / descripción</label><textarea data-module-field="fieldbook.sketch">${esc(d.sketch)}</textarea></div></div>${genericTable('fieldbook',[{field:'time',label:'Hora'},{field:'point',label:'Punto'},{field:'activity',label:'Actividad'},{field:'obs',label:'Observación'}],d.rows)}<div class="kpis">${kpi('Registros',String(r.count))}${kpi('Operador',esc(d.operator||current().meta.operator||'No definido'))}${kpi('Ubicación',esc(d.location||'No definida'))}</div></div>`}
function calcFieldbook(store=true){const d=current().modules.fieldbook;const res={rows:d.rows,count:d.rows.length,meta:d};if(store){d.result=res;save();renderFieldbook();status('Libreta actualizada')}return res}
const manualText={
compass:['Ingrese estaciones, distancias y rumbo o azimut.','Calcule azimut por rumbo cuadrantal.','Obtenga ΔN y ΔE.','Acumule coordenadas desde el punto inicial.','Si la poligonal es cerrada, distribuya el error por Bowditch o tránsito.'],
levelSimple:['Ingrese cota conocida, vista atrás y vista adelante.','Calcule HI = cota conocida + VA.','Calcule cota nueva = HI - VF.','El desnivel es cota nueva menos cota conocida.'],
levelCompound:['Registre VA en el punto de cota conocida.','Calcule HI para cada estación.','A cada VI o VF réstele la lectura a la HI.','En punto de cambio, la cota calculada pasa a ser base de una nueva HI.','Verifique ΣVA - ΣVF.'],
levelClosed:['Resuelva como nivelación compuesta.','Compare cota final calculada con cota final conocida.','Obtenga error de cierre.','Aplique corrección proporcional por distancia o por estaciones.','Revise semáforo de tolerancia.'],
station:['Ingrese coordenadas de estación y azimut base.','Para cada punto, sume AH al azimut base.','Con distancia inclinada y ángulo cenital calcule DH y desnivel.','Proyecte coordenadas X/Y y calcule Z.'],
theodolite:['Corrija lectura inversa horizontal restando 180°.','Promedie lectura directa e inversa corregida.','Sume al azimut base.','Radie coordenadas con distancia y ángulo vertical.'],
tacheometry:['Calcule intervalo estadimétrico s = LS - LI.','Calcule DH con K·s·cos²α.','Calcule desnivel con DH·tanα + HI - LM.','Proyecte coordenadas según azimut.'],
coords:['Use las herramientas para convertir rumbo/azimut y DMS/decimal.','Entre dos coordenadas calcule ΔE, ΔN, distancia y azimut.','Para radiación use E = E0 + D·sen Az y N = N0 + D·cos Az.'],
areas:['Ingrese vértices en orden.','Aplique la suma cruzada de Gauss.','El área es la mitad del valor absoluto de la diferencia.','El perímetro suma distancias entre vértices consecutivos.'],
contours:['Importe puntos X,Y,Z.','Defina equidistancia.','La app interpola una malla IDW.','Las isolíneas se dibujan como curvas de nivel básicas.'],
profiles:['Ingrese progresiva, cota terreno y rasante.','Calcule corte si terreno > rasante.','Calcule relleno si rasante > terreno.','Revise el perfil tipo guitarra.'],
volumes:['Ingrese áreas de corte/relleno por sección.','Calcule volumen entre secciones por áreas medias.','Acumule corte menos relleno.','Revise diagrama de masas.'],
curves:['Para curva horizontal calcule T, L, PC y PT.','Para curva vertical use parábola con g1, g2 y L.','Genere tabla de replanteo por intervalo.'],
gnss:['Ingrese latitud, longitud, h elipsoidal y ondulación N.','Calcule H = h - N.','Revise datum y sistema antes de usar en plano.'],
fieldbook:['Registre fecha, operador, equipo, clima y ubicación.','Anote actividades por hora y punto.','Exporte como reporte de campo.']
};
function renderManuals(){const keys=modules.filter(m=>!['dashboard','manuals'].includes(m.id));const active=state.manualTab||'compass';const m=modules.find(x=>x.id===active);$('#content').innerHTML=`<div class="card"><div class="section-title"><div><h3>Manuales por módulo</h3><small>Uso, ejemplo precargado y cálculo paso a paso.</small></div><span class="badge">Manual integrado</span></div><div class="tabs">${keys.map(x=>`<button class="tab ${x.id===active?'active':''}" data-action="manualTab" data-target="${x.id}">${x.title}</button>`).join('')}</div><div class="manual-box"><h3>${m.title}</h3><p>${m.desc}</p><h4>Cómo usar el módulo</h4><ol>${(manualText[active]||[]).map(s=>`<li>${s}</li>`).join('')}</ol><h4>Ejemplo precargado</h4>${manualExample(active)}<div class="toolbar no-print"><button class="btn" data-module="${active}">Abrir módulo</button><button class="btn secondary" data-action="calc" data-calc="${active}">Calcular ejemplo</button></div></div></div>`}
function manualExample(key){try{const calc=calcByKey(key,false);const rows=getExportRows(key);return `<p>El ejemplo ya está cargado en el proyecto actual. Al presionar calcular, se obtienen los resultados principales mostrados abajo:</p>${rows.length?resultTable(Object.keys(rows[0]).slice(0,8).map(k=>({field:k,label:k,num:typeof rows[0][k]==='number'})),rows.slice(0,8)):'<p class="muted">Este módulo genera un reporte narrativo.</p>'}`}catch(e){return `<p class="muted">Abra el módulo para revisar sus datos de entrada.</p>`}}
function calcByKey(key,store=true){const map={compass:calcCompass,levelSimple:calcLevelSimple,levelCompound:calcLevelCompound,levelClosed:calcLevelClosed,station:calcStation,theodolite:calcTheodolite,tacheometry:calcTacheometry,coords:calcCoords,areas:calcAreas,contours:calcContours,profiles:calcProfiles,volumes:calcVolumes,curves:calcCurves,gnss:calcGnss,fieldbook:calcFieldbook};return (map[key]||(()=>({})))(store)}
function plotPlan(points,closed=false){points=points.filter(p=>Number.isFinite(p.x)&&Number.isFinite(p.y));if(!points.length)return '<div class="empty">Sin puntos válidos.</div>';const xs=points.map(p=>p.x),ys=points.map(p=>p.y),minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys),W=900,H=380,padL=70,padR=36,padT=34,padB=58;const span=Math.max(maxX-minX||1,maxY-minY||1),cx=(minX+maxX)/2,cy=(minY+maxY)/2;const sx=x=>padL+((x-(cx-span/2))/span)*(W-padL-padR),sy=y=>H-padB-((y-(cy-span/2))/span)*(H-padT-padB);const pts=points.map(p=>`${sx(p.x)},${sy(p.y)}`).join(' '),poly=closed?pts+' '+`${sx(points[0].x)},${sy(points[0].y)}`:pts;const station=points.find(p=>p.station);const rays=station?points.filter(p=>p!==station).map(p=>`<line x1="${sx(station.x)}" y1="${sy(station.y)}" x2="${sx(p.x)}" y2="${sy(p.y)}" stroke="var(--line)" stroke-dasharray="5 5"/>`).join(''):'';let grid='';for(let i=0;i<=6;i++){const x=padL+i*(W-padL-padR)/6,y=padT+i*(H-padT-padB)/6;grid+=`<line x1="${x}" y1="${padT}" x2="${x}" y2="${H-padB}" stroke="var(--grid)"/><line x1="${padL}" y1="${y}" x2="${W-padR}" y2="${y}" stroke="var(--grid)"/>`;}return `<svg viewBox="0 0 ${W} ${H}">${grid}<rect x="${padL}" y="${padT}" width="${W-padL-padR}" height="${H-padT-padB}" fill="none" stroke="var(--line)"/><g transform="translate(${W-42},48)"><line x1="0" y1="24" x2="0" y2="-12" stroke="var(--text)" stroke-width="2"/><polygon points="0,-20 -7,-7 7,-7" fill="var(--text)"/><text x="0" y="-26" text-anchor="middle" fill="var(--text)" font-size="12" font-weight="700">N</text></g>${closed?`<polygon points="${poly}" fill="var(--primary)" opacity="0.10"/>`:''}${rays}<polyline points="${poly}" fill="none" stroke="var(--primary)" stroke-width="3"/>${points.map((p,i)=>`<circle cx="${sx(p.x)}" cy="${sy(p.y)}" r="${p.station?7:5}" fill="${p.station?'var(--danger)':'var(--accent)'}"/><text x="${sx(p.x)+8}" y="${sy(p.y)-8}" fill="var(--text)" font-size="12" font-weight="700">${esc(p.name||('P'+(i+1)))}</text><text x="${sx(p.x)+8}" y="${sy(p.y)+8}" fill="var(--muted)" font-size="10">E:${fmt(p.x)} N:${fmt(p.y)}</text>`).join('')}<text x="18" y="25" fill="var(--muted)" font-size="12">Vista en planta - retícula referencial</text></svg>`}
function plotProfileGuitar(rows){const pts=rows.filter(r=>Number.isFinite(r.elev)||Number.isFinite(r.elevCorr)).map((r,i)=>({x:num(r.dist,i),y:Number.isFinite(r.elevCorr)?r.elevCorr:r.elev,name:r.point||('P'+(i+1)),note:r.note||'',read:has(r.bs)?'VA '+r.bs:has(r.is)?'VI '+r.is:has(r.fs)?'VF '+r.fs:''}));if(!pts.length)return '<div class="empty">Sin perfil.</div>';return profileSvg(pts,[{label:'PUNTO',val:p=>p.name},{label:'PROG.',val:p=>fmt(p.x)},{label:'COTA',val:p=>fmt(p.y)},{label:'LECTURA',val:p=>p.read},{label:'OBS.',val:p=>p.note}],null)}
function plotRoadProfile(rows){const pts=rows.map(r=>({x:r.prog,y:r.terrain,name:String(r.prog),grade:r.grade,cut:r.cut,fill:r.fill}));return profileSvg(pts,[{label:'PROG.',val:p=>fmt(p.x)},{label:'TERRENO',val:p=>fmt(p.y)},{label:'RASANTE',val:p=>fmt(p.grade)},{label:'CORTE',val:p=>fmt(p.cut)},{label:'RELLENO',val:p=>fmt(p.fill)}],rows.map(r=>({x:r.prog,y:r.grade})))}
function profileSvg(pts,bands,gradePts){const allY=[...pts.map(p=>p.y),...(gradePts?gradePts.map(p=>p.y):[])],xs=pts.map(p=>p.x),minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...allY),maxY=Math.max(...allY),W=940,H=455,padL=68,padR=28,padT=28,padB=170,plotH=H-padT-padB,spanX=maxX-minX||1,spanY=maxY-minY||1;const sx=x=>padL+(x-minX)/spanX*(W-padL-padR),sy=y=>padT+plotH-(y-minY)/spanY*plotH;let grid='';for(let i=0;i<=5;i++){const y=padT+i*plotH/5;grid+=`<line x1="${padL}" y1="${y}" x2="${W-padR}" y2="${y}" stroke="var(--grid)"/><text x="${padL-8}" y="${y+4}" text-anchor="end" fill="var(--muted)" font-size="10">${fmt(maxY-i*spanY/5)}</text>`}pts.forEach(p=>{grid+=`<line x1="${sx(p.x)}" y1="${padT}" x2="${sx(p.x)}" y2="${plotH+padT}" stroke="var(--grid)"/>`});const terrain=pts.map(p=>`${sx(p.x)},${sy(p.y)}`).join(' '),grade=gradePts?gradePts.map(p=>`${sx(p.x)},${sy(p.y)}`).join(' '):'';const bandY=padT+plotH+12,bandH=26,colW=(W-padL-padR)/(pts.length||1);return `<svg viewBox="0 0 ${W} ${H}"><rect width="${W}" height="${H}" fill="transparent"/>${grid}<rect x="${padL}" y="${padT}" width="${W-padL-padR}" height="${plotH}" fill="none" stroke="var(--line)"/><polyline points="${terrain}" fill="none" stroke="var(--primary)" stroke-width="3"/>${grade?`<polyline points="${grade}" fill="none" stroke="var(--accent)" stroke-width="3" stroke-dasharray="8 5"/>`:''}${pts.map(p=>`<circle cx="${sx(p.x)}" cy="${sy(p.y)}" r="4" fill="var(--primary)"/>`).join('')}<text x="18" y="24" fill="var(--muted)" font-size="12">Perfil longitudinal tipo guitarra</text>${grade?'<text x="760" y="24" fill="var(--accent)" font-size="12">Rasante</text><text x="690" y="24" fill="var(--primary)" font-size="12">Terreno</text>':''}${bands.map((b,bi)=>`<g><rect x="8" y="${bandY+bi*bandH}" width="${padL-8}" height="${bandH}" fill="rgba(127,127,127,.08)" stroke="var(--line)"/><text x="${padL-10}" y="${bandY+bi*bandH+17}" text-anchor="end" fill="var(--text)" font-size="10" font-weight="700">${b.label}</text>${pts.map((p,i)=>`<rect x="${padL+i*colW}" y="${bandY+bi*bandH}" width="${colW}" height="${bandH}" fill="transparent" stroke="var(--line)"/><text x="${padL+i*colW+colW/2}" y="${bandY+bi*bandH+17}" text-anchor="middle" fill="var(--text)" font-size="10">${esc(b.val(p))}</text>`).join('')}</g>`).join('')}</svg>`}
function idw(points,x,y){let sw=0,sz=0;for(const p of points){const d=Math.hypot(x-p.x,y-p.y)||0.001,w=1/(d*d);sw+=w;sz+=p.z*w}return sz/sw}
function plotContours(rows,interval){const pts=rows.map(r=>({name:r.point,x:num(r.x),y:num(r.y),z:num(r.z)})).filter(p=>Number.isFinite(p.x)&&Number.isFinite(p.y)&&Number.isFinite(p.z));if(!pts.length)return '<div class="empty">Sin puntos.</div>';const W=900,H=380,pad=45,xs=pts.map(p=>p.x),ys=pts.map(p=>p.y),zs=pts.map(p=>p.z),minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys),minZ=Math.min(...zs),maxZ=Math.max(...zs);const sx=x=>pad+(x-minX)/(maxX-minX||1)*(W-2*pad),sy=y=>H-pad-(y-minY)/(maxY-minY||1)*(H-2*pad);let levels=[];for(let z=Math.ceil(minZ/interval)*interval;z<=maxZ+1e-9;z+=interval)levels.push(z);let lines='';levels.forEach((lv,li)=>{const ptsNear=[];for(let gx=0;gx<=30;gx++){for(let gy=0;gy<=18;gy++){const x=minX+(maxX-minX)*gx/30,y=minY+(maxY-minY)*gy/18,z=idw(pts,x,y);if(Math.abs(z-lv)<interval*.18)ptsNear.push({x,y})}}lines+=ptsNear.map(p=>`<circle cx="${sx(p.x)}" cy="${sy(p.y)}" r="1.6" fill="var(--primary)" opacity="${.35+.5*li/(levels.length||1)}"/>`).join('');if(ptsNear[0])lines+=`<text x="${sx(ptsNear[0].x)+4}" y="${sy(ptsNear[0].y)-4}" fill="var(--primary)" font-size="10">${fmt(lv)}</text>`});return `<svg viewBox="0 0 ${W} ${H}"><rect x="${pad}" y="${pad}" width="${W-2*pad}" height="${H-2*pad}" fill="rgba(127,127,127,.05)" stroke="var(--line)"/>${lines}${pts.map(p=>`<circle cx="${sx(p.x)}" cy="${sy(p.y)}" r="5" fill="var(--accent)"/><text x="${sx(p.x)+7}" y="${sy(p.y)-7}" fill="var(--text)" font-size="11">${esc(p.name)} ${fmt(p.z)}</text>`).join('')}<text x="18" y="24" fill="var(--muted)" font-size="12">Curvas de nivel por interpolación IDW referencial</text></svg>`}
function plotMassHaul(rows){const pts=rows.map(r=>({x:r.dist,y:r.mass,name:r.section}));if(!pts.length)return '<div class="empty">Sin datos.</div>';const xs=pts.map(p=>p.x),ys=pts.map(p=>p.y),minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys,0),maxY=Math.max(...ys,0),W=900,H=380,pad=48;const sx=x=>pad+(x-minX)/(maxX-minX||1)*(W-2*pad),sy=y=>H-pad-(y-minY)/(maxY-minY||1)*(H-2*pad);const base=sy(0),pl=pts.map(p=>`${sx(p.x)},${sy(p.y)}`).join(' ');return `<svg viewBox="0 0 ${W} ${H}"><line x1="${pad}" y1="${base}" x2="${W-pad}" y2="${base}" stroke="var(--line)" stroke-width="2"/><polyline points="${pl}" fill="none" stroke="var(--primary)" stroke-width="3"/>${pts.map(p=>`<circle cx="${sx(p.x)}" cy="${sy(p.y)}" r="4" fill="${p.y>=0?'var(--success)':'var(--danger)'}"/><text x="${sx(p.x)+6}" y="${sy(p.y)-6}" fill="var(--text)" font-size="10">${fmt(p.y)}</text><text x="${sx(p.x)}" y="${H-18}" text-anchor="middle" fill="var(--muted)" font-size="10">${esc(p.name)}</text>`).join('')}<text x="18" y="24" fill="var(--muted)" font-size="12">Diagrama de masas: corte (+) / relleno (-)</text></svg>`}
function plotCurveSketch(h){const W=900,H=320,cx=450,cy=280,R=220,a1=220,a2=320;const arc=`M ${cx+R*Math.cos(rad(a1))} ${cy+R*Math.sin(rad(a1))} A ${R} ${R} 0 0 1 ${cx+R*Math.cos(rad(a2))} ${cy+R*Math.sin(rad(a2))}`;return `<svg viewBox="0 0 ${W} ${H}"><path d="${arc}" fill="none" stroke="var(--primary)" stroke-width="5"/><line x1="120" y1="${cy-80}" x2="${cx}" y2="${cy}" stroke="var(--line)" stroke-width="2"/><line x1="${cx}" y1="${cy}" x2="780" y2="${cy-80}" stroke="var(--line)" stroke-width="2"/><circle cx="${cx}" cy="${cy}" r="5" fill="var(--danger)"/><text x="${cx+8}" y="${cy-8}" fill="var(--text)">PI ${fmt(h.PI)}</text><text x="150" y="80" fill="var(--text)">PC ${fmt(h.PC)}</text><text x="650" y="80" fill="var(--text)">PT ${fmt(h.PT)}</text><text x="18" y="24" fill="var(--muted)">Croquis de curva horizontal</text></svg>`}
function plotVerticalCurve(rows){if(!rows.length)return '';const pts=rows.map(r=>({x:r.x,y:r.elev})),W=900,H=260,pad=40,xs=pts.map(p=>p.x),ys=pts.map(p=>p.y),minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys);const sx=x=>pad+(x-minX)/(maxX-minX||1)*(W-2*pad),sy=y=>H-pad-(y-minY)/(maxY-minY||1)*(H-2*pad),pl=pts.map(p=>`${sx(p.x)},${sy(p.y)}`).join(' ');return `<svg viewBox="0 0 ${W} ${H}"><polyline points="${pl}" fill="none" stroke="var(--accent)" stroke-width="3"/>${pts.map(p=>`<circle cx="${sx(p.x)}" cy="${sy(p.y)}" r="4" fill="var(--accent)"/>`).join('')}<text x="18" y="24" fill="var(--muted)">Curva vertical parabólica</text></svg>`}
function getExportRows(key){const d=current().modules[key];if(!d)return[];if(d.result?.rows)return d.result.rows;if(d.result?.points)return d.result.points;if(key==='curves')return d.result?.v?.table||calcCurves(false).v.table;if(Array.isArray(d.rows))return d.rows;if(d.result)return [d.result];return[]}
function toCSV(rows){if(!rows.length)return'';const h=[...new Set(rows.flatMap(r=>Object.keys(r)))];return h.join(',')+'\n'+rows.map(r=>h.map(k=>`"${String(r[k]??'').replace(/"/g,'""')}"`).join(',')).join('\n')}
function download(name,content,type='text/plain'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function exportCSV(key){calcByKey(key,false);download(`${key}_${Date.now()}.csv`,toCSV(getExportRows(key)),'text/csv;charset=utf-8')}
function exportJSON(key){download(`${key}_${Date.now()}.json`,JSON.stringify(current().modules[key],null,2),'application/json')}
function exportXLS(key){const rows=getExportRows(key);if(!rows.length)return;const h=Object.keys(rows[0]);const html='<table><tr>'+h.map(x=>`<th>${esc(x)}</th>`).join('')+'</tr>'+rows.map(r=>'<tr>'+h.map(x=>`<td>${esc(r[x]??'')}</td>`).join('')+'</tr>').join('')+'</table>';download(`${key}_${Date.now()}.xls`,html,'application/vnd.ms-excel')}
function parseCSV(text){const lines=String(text).split(/\r?\n/).filter(l=>l.trim());if(!lines.length)return[];const split=line=>{const out=[];let cur='',q=false;for(let ch of line){if(ch==='"'){q=!q;continue}if((ch===','||ch===';')&&!q){out.push(cur.trim());cur=''}else cur+=ch}out.push(cur.trim());return out};const heads=split(lines[0]);return lines.slice(1).map(line=>{const vals=split(line),o={};heads.forEach((h,i)=>o[h]=vals[i]??'');return o})}
function importFile(key,file){if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const txt=reader.result;let rows=file.name.toLowerCase().endsWith('.json')?JSON.parse(txt):parseCSV(txt);if(!Array.isArray(rows))rows=rows.rows||rows.data||[];if(current().modules[key]?.rows){current().modules[key].rows=rows;save();renderContent();status('Datos importados')}}catch(e){alert('No se pudo importar: '+e.message)}};reader.readAsText(file)}
function blankFor(key){const d=current().modules[key];if(d?.rows?.[0]){const b=JSON.parse(JSON.stringify(d.rows[0]));Object.keys(b).forEach(k=>b[k]='');return b}return {point:'',x:'',y:'',z:''}}
function addRow(key,index=null,dup=false){const rows=current().modules[key]?.rows;if(!rows)return;let b=dup&&index!==null?JSON.parse(JSON.stringify(rows[index])):blankFor(key);rows.splice(index===null?rows.length:index+1,0,b);save();renderContent()}
function delRow(key,index){const rows=current().modules[key]?.rows;if(rows&&rows.length>1){rows.splice(index,1);save();renderContent()}else alert('Debe quedar al menos una fila')}
function loadExamples(){const id=current().id,name=current().meta.name,meta=current().meta;const fresh=defaultProject(name);fresh.id=id;fresh.meta={...fresh.meta,...meta};state.projects[state.projects.findIndex(p=>p.id===id)]=fresh;save();render();status('Ejemplos precargados restaurados')}
function updateInput(el){const p=current();if(el.dataset.bind){setByPath(p,el.dataset.bind,el.type==='number'?num(el.value):el.value);save();applyAppearance();renderProjectSelect();return}if(el.dataset.moduleField){setByPath(p.modules,el.dataset.moduleField,el.type==='number'?num(el.value):el.value);save();return}if(el.dataset.cell){setByPath(p.modules,el.dataset.cell,el.type==='number'?num(el.value):el.value);save();return}}
document.addEventListener('click',e=>{const mod=e.target.closest('[data-module]');if(mod){state.active=mod.dataset.module;render();return}const btn=e.target.closest('[data-action]');if(!btn)return;const a=btn.dataset.action,target=btn.dataset.target,index=btn.dataset.index!==undefined?parseInt(btn.dataset.index):null;if(a==='toggleFormulas'){state.formulas=!state.formulas;localStorage.setItem('topopro_v3_formulas',state.formulas);renderContent()}if(a==='saveProject'){save()}if(a==='newProject'){const p=defaultProject('Nuevo proyecto');state.projects.push(p);state.activeId=p.id;save();render()}if(a==='duplicateProject'){const p=JSON.parse(JSON.stringify(current()));p.id=uid();p.meta.name+=' copia';state.projects.push(p);state.activeId=p.id;save();render()}if(a==='deleteProject'){if(state.projects.length===1)return alert('No se puede eliminar el único proyecto.');if(confirm('¿Eliminar este proyecto?')){state.projects=state.projects.filter(p=>p.id!==state.activeId);state.activeId=state.projects[0].id;save();render()}}if(a==='backupProject')download(`${current().meta.name}_respaldo.json`,JSON.stringify(current(),null,2),'application/json');if(a==='clearLogo'){current().meta.logo='';save();render()}if(a==='loadExamples')loadExamples();if(a==='calc')calcByKey(btn.dataset.calc,true);if(a==='addRow')addRow(target);if(a==='insertRow')addRow(target,index,false);if(a==='dupRow')addRow(target,index,true);if(a==='delRow')delRow(target,index);if(a==='exportCSV')exportCSV(target);if(a==='exportJSON')exportJSON(target);if(a==='exportXLS')exportXLS(target);if(a==='printReport')window.print();if(a==='showManual'){state.manualTab=target;state.active='manuals';render()}if(a==='manualTab'){state.manualTab=target;renderManuals()}});
document.addEventListener('input',e=>{if(e.target.matches('[data-bind],[data-module-field],[data-cell]'))updateInput(e.target)});
document.addEventListener('change',e=>{if(e.target.id==='projectSelect'){state.activeId=e.target.value;save();render();return}if(e.target.id==='themeToggle'){state.theme=e.target.checked?'dark':'light';localStorage.setItem('topopro_v3_theme',state.theme);render();return}if(e.target.id==='logoInput'){const f=e.target.files[0];if(f){const r=new FileReader();r.onload=()=>{current().meta.logo=r.result;save();render()};r.readAsDataURL(f)}return}if(e.target.dataset.import)importFile(e.target.dataset.import,e.target.files[0]);if(e.target.matches('[data-bind],[data-module-field],[data-cell]')){updateInput(e.target);renderContent()}});
load();render();
})();
